"""
Django settings for Timetable_Generator_Project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s)8ejdhckib#scqu@+rczpi^z7hwxmwaer*!0!3klqs_*(6y@)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['raul05madalin.pythonanywhere.com', '127.0.0.1']

# GOOGLE_CALENDAR_CLIENT_ID = '272845606315-prllneihspnm2r7mbrkvf6jgv5trdu8b.apps.googleusercontent.com'
# GOOGLE_CALENDAR_CLIENT_SECRET = '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'
# GOOGLE_CALENDAR_REDIRECT_URI = 'http://127.0.0.1:8000/google-calendar/auth/callback/'

GOOGLE_CALENDAR_CLIENT_ID = '315725404428-e6m6o5gk311lgsel702i7e3cvilr03bs.apps.googleusercontent.com'
GOOGLE_CALENDAR_CLIENT_SECRET = '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'
GOOGLE_CALENDAR_REDIRECT_URI = 'http://127.0.0.1:8000/google_calendar/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Timetable',
    'django_prometheus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Timetable_Generator_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Timetable_Generator_Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'raul05madalin$Timetable-Generator-Project',
    #     'USER': 'raul05madalin',
    #     'PASSWORD': 'Timetable-Generator-Project',
    #     'HOST': 'raul05madalin.mysql.pythonanywhere-services.com',
    #     'PORT': '3306',
    # },
    # 'default': {    # local_db
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'timetable_generator_project',
    #     'USER': 'root',
    #     'PASSWORD': '',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    # },
     'default': {    # local_db
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'database_timetable',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/raul05madalin/Timetable-Generator-Project/Timetable-Generator-Project/static/'
MEDIA_ROOT = '/home/raul05madalin/Timetable-Generator-Project/Timetable-Generator-Project/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    #'path.to.YourEmailBackend',  # Replace with the actual path to your email-based backend
]